import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useWeibo } from "@/api/hooks";
import { SpotlightCard } from "@/components/reactbits/SpotlightCard";
import { Heart, MessageCircle, Share2, Repeat2 } from "lucide-react";
export default function Weibo() {
    const [uidFilter, setUidFilter] = useState("");
    const uid = uidFilter ? Number(uidFilter) : undefined;
    const { data, isLoading } = useWeibo(uid, 100);
    return (_jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("input", { className: "bg-surface-2 border border-hairline rounded-md px-3 py-2 text-sm text-ink placeholder:text-ink-subtle focus:outline-none focus:border-primary w-64", placeholder: "\u6309 UID \u8FC7\u6EE4 (\u7559\u7A7A\u663E\u793A\u5168\u90E8)", value: uidFilter, onChange: (e) => setUidFilter(e.target.value.replace(/\D/g, "")) }), data && _jsxs("span", { className: "text-ink-subtle text-xs", children: ["\u5171 ", data.length, " \u6761"] })] }), isLoading && _jsx("div", { className: "text-ink-subtle", children: "\u52A0\u8F7D\u5FAE\u535A..." }), _jsxs("div", { className: "flex flex-col gap-3", children: [data?.map((w) => (_jsxs(SpotlightCard, { className: "p-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "text-ink-subtle text-xs font-mono", children: [w.weibo_id, " \u00B7 uid ", w.uid] }), _jsxs("div", { className: "flex items-center gap-1.5 text-xs", children: [w.is_retweet && _jsx(Repeat2, { size: 12, className: "text-ink-subtle" }), _jsx("span", { className: "text-ink-subtle", children: w.source ?? "" }), _jsx("span", { className: "text-ink-subtle", children: w.created_at ? new Date(w.created_at).toLocaleString() : "" })] })] }), _jsx("div", { className: "text-ink leading-relaxed whitespace-pre-wrap break-words", children: w.text }), w.pic_urls.length > 0 && (_jsx("div", { className: "mt-3 flex gap-2 flex-wrap", children: w.pic_urls.slice(0, 4).map((u) => (_jsx("img", { src: u, alt: "", className: "h-20 w-20 rounded border border-hairline object-cover", onError: (e) => (e.currentTarget.style.display = "none"), referrerPolicy: "no-referrer" }, u))) })), _jsxs("div", { className: "flex gap-5 mt-3 pt-3 border-t border-hairline text-xs text-ink-subtle", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Heart, { size: 12 }), " ", w.attitudes_count] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(MessageCircle, { size: 12 }), " ", w.comments_count] }), _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Share2, { size: 12 }), " ", w.reposts_count] })] })] }, w.weibo_id))), data?.length === 0 && (_jsxs("div", { className: "text-center py-20 text-ink-subtle", children: ["\u6682\u65E0\u5FAE\u535A. \u7528 ", _jsx("code", { className: "text-primary", children: "wcn run -u <uid>" }), " \u6293\u4E00\u4E9B."] }))] })] }));
}
